Resources:
  CommentTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ChatRoom
      AttributeDefinitions:
        - AttributeName: ownerId
          AttributeType: S
      KeySchema:
        - AttributeName: ownerId
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
