Resources:
  CommentTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Comment
      AttributeDefinitions:
        - AttributeName: commentId
          AttributeType: S
      KeySchema:
        - AttributeName: commentId
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
