Resources:
  FriendsListTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: FriendsList
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5